# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: LocalAgent

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://devops.lunarcolony.dev/Projects/SamSulekBot/_git/SamSulekBot'
    sourceGitRepositoryPersonalAccessToken: '$(SrcPat)'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://github.com/dolph1nn/samsulekbot'
    destinationGitRepositoryPersonalAccessToken: '$(DestPat)'

- task: DotNetCoreCLI@2
  condition: contains(variables['Build.SourceVersionMessage'], '[BUILD]')
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(BinariesDirectory) --source $(NuGetTemp)'

- task: ArchiveFiles@2
  condition: contains(variables['Build.SourceVersionMessage'], '[BUILD]')
  inputs:
    rootFolderOrFile: '$(BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'tar'
    archiveFile: '$(ArtifactStagingDirectory)/$(Build.SourceVersion).tgz'
    replaceExistingArchive: true