# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: LocalAgent

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: 'https://devops.lunarcolony.dev/Projects/SamSulekBot/_git/SamSulekBot'
    sourceGitRepositoryPersonalAccessToken: '$(SrcPat)'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://github.com/dolph1nn/samsulekbot'
    destinationGitRepositoryPersonalAccessToken: '$(DestPat)'

- task: DotNetCoreCLI@2
  condition: contains(variables['Build.SourceVersionMessage'], '[BUILD]')
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(BinariesDirectory)'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(BinariesDirectory)'
    Contents: '**/*.{xml,pdb}'
    
- task: ArchiveFiles@2
  condition: contains(variables['Build.SourceVersionMessage'], '[BUILD]')
  inputs:
    rootFolderOrFile: '$(BinariesDirectory)'
    includeRootFolder: false
    archiveType: '7z'
    sevenZipCompression: 'maximum'
    archiveFile: '$(ArtifactStagingDirectory)/$(Build.SourceVersion).7z'
    replaceExistingArchive: true